CC=g++
CFLAGS=-Wall -pedantic -g
TARGETS=./IntegralMethod.cpp \
./MonteCarloMethod.cpp \
./RectanglesMethod.cpp \
./Results.cpp \
./SimpsonsMethod.cpp \
./TrapezeMethod.cpp \
./Utilities.cpp \
./main.cpp 

all: 
	$(CC) $(CFLAGS) -o main $(TARGETS) 
